Added toggle for toast and custom toast text
Purus/launch_review pull request #43
Opened 2021-12-10 11:16 UTC by broderbluff

Added the ability to use a custom text for toast - And the ability to the user wants to show a toast or not.

2021-12-10 11:17 UTC, broderbluff commented
Added the ability to use a custom text for toast - And the ability to the user wants to show a toast or not.

2022-03-11 12:16 UTC, PieterPicup commented
@Purus Could you please try get this merged in and published?
I have made my own implimentation of this locally for now but it would be a great addition.

My use case is I need the user to update their app. I was just going to add an option for showToast but the addition here of the message is great.

2022-04-24 13:01 UTC, ifnotak requested changes

2022-04-24 13:01 UTC, ifnotak commented on android/src/main/java/com/iyaffle/launchreview/LaunchReviewPlugin.java
> +            if (toastMessage == null){
Please format your code! Thanks!

2022-08-15 08:22 UTC, merged